services:

    App\DataFixtures\AppFixtures:
        arguments: ['@fidry_alice_data_fixtures.loader.doctrine']
        tags: [{ name: doctrine.fixture.orm }]

    App\DataFixtures\Processor\UserProcessor:
        arguments: ['@Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface']
        tags: [{ name: fidry_alice_data_fixtures.processor }]

    App\DataFixtures\Provider\CollectionProvider:
        tags: [{ name: nelmio_alice.faker.provider }]
